language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
sudo: required
dist: xenial
cache:
  directories:
    - ~/.cache/pip
install:
  - pip install numpy cython
  - python setup.py install
script:
  - python tests/test_jenks.py
addons:
  apt:
    packages:
      - python-numpy
      - python3-numpy
